name: Gradle CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Linting with ktlint
      run: gradle ktlintCheck

    - name: Test with gradle
      run: gradle test
